version: '3.7'
x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      NODE_MAJOR: '14'
  environment: &env
    NODE_ENV: development
    MIX_ENV: ${MIX_ENV:-dev}
  image: phoenix-sandbox:1.0.0

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/usr/local/sandbox:cached
  environment:
    <<: *env
  depends_on:
    - postgres

services:
  runner:
    <<: *backend
    command: /bin/bash
  phoenix:
    <<: *backend
    command: mix phx.server
    ports:
      - 4000:4000
  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
volumes:
  postgres: